{% set name = "nionswift-tool" %}
{% set macos_app = "Nion Swift" %}
{% set app_dir = "NionSwiftLauncher" %}
{% set macos_exe = "Nion Swift" %}
{% set linux_exe = "NionSwiftLauncher" %}
{% set win_exe = "NionSwift" %}
{% set summary = "A native launcher for Nion Swift." %}

{% set version = "0.4.14" %}

{% set name_u = name|replace('-', '_') %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0
  skip: true  # [py2k or python_impl == 'pypy']
  entry_points:
    - {{ name }} = nion.{{ name_u }}.command:main
  binary_relocation: false
  ignore_prefix_files: true
  detect_binary_files_with_prefix: false
  missing_dso_whitelist: '**/*'
  ignore_run_exports:
    - qt

requirements:
  host:
    - python
    - pip
    - setuptools
    - numpy 1.21.*
  run:
    - python
    - setuptools

test:
  commands:
    - test -f "$PREFIX/bin/{{ name }}"  # [osx]
    - test -f "$PREFIX/bin/{{ macos_app }}.app/Contents/MacOS/{{ macos_exe }}"  # [osx]
    - test -f "$PREFIX/bin/{{ macos_app }}.app/Contents/Resources/bootstrap.py"  # [osx]
    - test -f "$PREFIX/bin/{{ name }}"  # [linux]
    - test -f "$PREFIX/bin/{{ app_dir }}/{{ linux_exe }}"  # [linux]
    - test -f "$PREFIX/bin/{{ app_dir }}/bootstrap.py"  # [linux]
    - if not exist "%PREFIX%\\Scripts\\{{ name }}.exe" exit 1  # [win]
    - if not exist "%PREFIX%\\Scripts\\{{ app_dir }}\\{{ win_exe }}.exe" exit 1  # [win]
    - if not exist "%PREFIX%\\Scripts\\{{ app_dir }}\\bootstrap.py" exit 1  # [win]

about:
  home: http://github.com/nion-software/{{ name }}
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - NOTICES
  summary: {{ summary }}
  dev_url: https://github.com/nion-software/{{ name }}

extra:
  recipe-maintainers:
    - cmeyer
