{% set name = "nionswift-tool" %}
{% set version = "0.4.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 6
  skip: true  # [py2k or python_impl == 'pypy']
  entry_points:
    - nionswift-tool = nion.nionswift_tool.command:main
  binary_relocation: false
  ignore_prefix_files: true
  detect_binary_files_with_prefix: false
  missing_dso_whitelist: '**/*'
  ignore_run_exports:
    - qt

requirements:
  host:
    - python
    - pip
    - setuptools
    - numpy 1.14.*
  run:
    - python

test:
  commands:
    - test -f "$PREFIX/bin/nionswift-tool"  # [osx]
    - test -f "$PREFIX/bin/Nion Swift.app/Contents/MacOS/Nion UI Launcher"  # [osx]
    - test -f "$PREFIX/bin/Nion Swift.app/Contents/Resources/bootstrap.py"  # [osx]
    - test -f "$PREFIX/bin/nionswift-tool"  # [linux]
    - test -f "$PREFIX/bin/NionSwiftLauncher/NionSwiftLauncher"  # [linux]
    - test -f "$PREFIX/bin/NionSwiftLauncher/bootstrap.py"  # [linux]
    - if not exist "%PREFIX%\\Scripts\\nionswift-tool.exe" exit 1  # [win]
    - if not exist "%PREFIX%\\Scripts\\NionSwiftLauncher\\NionSwiftLauncher.exe" exit 1  # [win]
    - if not exist "%PREFIX%\\Scripts\\NionSwiftLauncher\\bootstrap.py" exit 1  # [win]

about:
  home: http://github.com/nion-software/{{ name }}
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - NOTICES
  summary: A native launcher for Nion UI apps.
  dev_url: https://github.com/nion-software/{{ name }}

extra:
  recipe-maintainers:
    - cmeyer
