{% set name = "nionui-tool" %}
{% set version = "0.4.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 6
  skip: true  # [py2k or python_impl == 'pypy']
  entry_points:
    - nionui-tool = nion.nionui_tool.command:main
  binary_relocation: false
  ignore_prefix_files: true
  detect_binary_files_with_prefix: false
  missing_dso_whitelist: '**/*'
  ignore_run_exports:
    - qt

requirements:
  host:
    - python
    - pip
    - setuptools
    - numpy 1.14.*
  run:
    - python

test:
  commands:
    - test -f "$PREFIX/bin/nionui-tool"  # [osx]
    - test -f "$PREFIX/bin/Nion UI Launcher.app/Contents/MacOS/Nion UI Launcher"  # [osx]
    - test -f "$PREFIX/bin/Nion UI Launcher.app/Contents/Resources/bootstrap.py"  # [osx]
    - test -f "$PREFIX/bin/nionui-tool"  # [linux]
    - test -f "$PREFIX/bin/NionUILauncher/NionUILauncher"  # [linux]
    - test -f "$PREFIX/bin/NionUILauncher/bootstrap.py"  # [linux]
    - if not exist "%PREFIX%\\Scripts\\nionui-tool.exe" exit 1  # [win]
    - if not exist "%PREFIX%\\Scripts\\NionUILauncher\\NionUILauncher.exe" exit 1  # [win]
    - if not exist "%PREFIX%\\Scripts\\NionUILauncher\\bootstrap.py" exit 1  # [win]

about:
  home: http://github.com/nion-software/{{ name }}
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - NOTICES
  summary: A native launcher for Nion UI apps.
  dev_url: https://github.com/nion-software/{{ name }}

extra:
  recipe-maintainers:
    - cmeyer
